# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Next.js Build
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
---
name: 'Next.js Build'
description: 'Build next.js project'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Inputs
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
inputs:
  rd_github_package_token:
    description: 'Personal Access Token Stored in Secrets'
    required: true

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Runs
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    # Set our Registry
    - id: registry
      run: |
        echo "_auth=false" >> ~/.npmrc
        echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
        echo "@red-digital:registry=https://npm.pkg.github.com" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.rd_github_package_token }}" >> ~/.npmrc
      shell: bash

    # Clean Install Dependencies
    - run: npm ci
      shell: bash

    # Build and Export
    - run: npm run export
      shell: bash

    # Cache our Build
    - uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
